preload = /home/peroyhav/.config/hypr/NorthernLightsDevel.png
wallpaper = eDP-1, /home/peroyhav/.config/hypr/NorthernLightsDevel.png
wallpaper = HDMI-A-1, /home/peroyhav/.config/hypr/NorthernLightsDevel.png
